apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-volume-data
  namespace: gitlab  
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/slonnik/pstorage/gitlab/data"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-volume-logs
  namespace: gitlab
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/slonnik/pstorage/gitlab/logs"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-volume-config
  namespace: gitlab
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/slonnik/pstorage/gitlab/config"
